### ISSUE TITLE
[BUG] Viewing certain Vanilla Heartless crash the game.

### ISSUE THREAD

**Issue by TopazTK** [KH-ReFined/KH-ReFined#132]
**Re:Fined Version:**
v4.10

**Game in Question:**
Kingdom Hearts II

**Bug Description:**
When you go into the journal and view certain Heartless on the Vanilla Palette (Ex. Thresholder), it won't load the Heartless. Attempting to full view it will softlock the game.

**Reproduction Steps:**
-> Set Heartless Palette to "Vanilla"
-> Go into the Journal
-> Open the entry for the problematic Heartless
-> ???
-> Profit!

**Screenshots/Video:**
![Screenshot_40](https://github.com/TopazTK/KH-ReFined/assets/95656963/7b4439c3-280a-4ec4-8adc-27e2a6b78269)
![Screenshot_41](https://github.com/TopazTK/KH-ReFined/assets/95656963/2ac8ae67-aef4-4477-8d3e-237bc2ec9753)

**Comment by biiown** [comment]
this also happens with trick ghost so far.

**Comment by TopazTK** [comment]
Works for me. Odd. I cannot reproduce this yet but I am trying.

**Comment by KHOmega** [comment]
As this cannot be reproduced, can be attributed to a potentially due to a faulty OpenKH patch installation, is several patches old, and has attached images below show both Heartless working on the latest patch as of this writing (v5.00), I will be closing this issue. 

![image](https://github.com/KH-ReFined/KH-ReFined/assets/93887977/1d45234a-0bd4-4c7f-8023-314b10d2b6c5)
![image](https://github.com/KH-ReFined/KH-ReFined/assets/93887977/beb67868-779b-4341-9222-00934f99c9aa)

**Comment by KHOmega** [comment]
Issue is still present in V5.00. Results in a soft-lock when trying to view the model of the following Heartless in Jiminy's Journal using Vanilla Heartless Addon:

- Trick Ghost
- Magic Phantom
- Thresholder
- Grim Reaper
- Ground Shaker
- Storm Rider

![image](https://github.com/KH-ReFined/KH-ReFined/assets/93887977/91a0e641-eae7-4187-9e7f-8dce6193fa76)
![image](https://github.com/KH-ReFined/KH-ReFined/assets/93887977/a45f2139-6074-4d43-83d4-795b9a608dd8)
![image](https://github.com/KH-ReFined/KH-ReFined/assets/93887977/61f76865-0938-4007-ab72-2c680d739e9c)
![image](https://github.com/KH-ReFined/KH-ReFined/assets/93887977/6a4175e6-6989-4297-87b5-5249e6b34449)
![image](https://github.com/KH-ReFined/KH-ReFined/assets/93887977/2728c887-b3b1-47a0-babc-f0f3b39b3a74)
![image](https://github.com/KH-ReFined/KH-ReFined/assets/93887977/4c7ae54f-52b1-4edb-a682-78ff0b5c8db8)

**Comment by TopazTK** [comment]
Yea but why tf

**Comment by TopazTK** [comment]
I got it to reproduce, I have no fucking idea why this happens, tf?

**Comment by TopazTK** [comment]
Fixed. Closing.
