### ISSUE TITLE
[BUG] Main not found

### ISSUE THREAD

**Issue by Onre64** [KH-ReFined/KH-ReFined#143]
**Re:Fined Version:**
4.20
**Game in Question:**
KH2

**Bug Description:**
Game gives me error that main patch not found

**Reproduction Steps:**
Start the game

**Screenshots/Video:**

![Crash](https://github.com/KH-ReFined/KH-ReFined/assets/111638647/c2ba1cc5-201c-4e56-91e4-5bd257634a3f)

**Comment by TopazTK** [comment]
The error literally tells you what you did wrong.
Closing.
